export const demoData = [
  {
    id: 1,
    airlineName: "Air India",
    airlineModel: "Boeing 777",
    airlineCode: "AI",
    fromAirport: {
      code: "DEL",
      name: "Indira Gandhi International Airport",
      city: "Delhi",
    },
    toAirport: {
      code: "BOM",
      name: "Chhatrapati Shivaji Maharaj International Airport",
      city: "Mumbai",
    },
    departureTime: "2024-04-27T09:30:00",
    arrivalTime: "2024-04-27T12:00:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 550,
      children: 400,
      infant: 120,
    },
    stops: 0,
    duration: "2h 30m",
  },
  {
    id: 2,
    airlineName: "IndiGo",
    airlineModel: "Airbus A320",
    airlineCode: "6E",
    fromAirport: {
      code: "BOM",
      name: "Chhatrapati Shivaji Maharaj International Airport",
      city: "Mumbai",
    },
    toAirport: {
      code: "DEL",
      name: "Indira Gandhi International Airport",
      city: "Delhi",
    },
    departureTime: "2024-04-27T11:45:00",
    arrivalTime: "2024-04-27T14:15:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 600,
      children: 450,
      infant: 130,
    },
    stops: 0,
    duration: "2h 30m",
  },
  {
    id: 3,
    airlineName: "SpiceJet",
    airlineModel: "Boeing 737",
    airlineCode: "SG",
    fromAirport: {
      code: "CCU",
      name: "Netaji Subhas Chandra Bose International Airport",
      city: "Kolkata",
    },
    toAirport: {
      code: "MAA",
      name: "Chennai International Airport",
      city: "Chennai",
    },
    departureTime: "2024-04-27T13:00:00",
    arrivalTime: "2024-04-27T15:30:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 480,
      children: 350,
      infant: 100,
    },
    stops: 1,
    duration: "2h 30m",
  },
  {
    id: 4,
    airlineName: "Vistara",
    airlineModel: "Airbus A320neo",
    airlineCode: "UK",
    fromAirport: {
      code: "DEL",
      name: "Indira Gandhi International Airport",
      city: "Delhi",
    },
    toAirport: {
      code: "MAA",
      name: "Chennai International Airport",
      city: "Chennai",
    },
    departureTime: "2024-04-27T10:15:00",
    arrivalTime: "2024-04-27T12:45:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 580,
      children: 420,
      infant: 110,
    },
    stops: 0,
    duration: "2h 30m",
  },

  {
    id: 5,
    airlineName: "GoAir",
    airlineModel: "Airbus A320neo",
    airlineCode: "G8",
    fromAirport: {
      code: "MAA",
      name: "Chennai International Airport",
      city: "Chennai",
    },
    toAirport: {
      code: "BLR",
      name: "Kempegowda International Airport",
      city: "Bengaluru",
    },
    departureTime: "2024-04-27T14:30:00",
    arrivalTime: "2024-04-27T16:00:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 520,
      children: 380,
      infant: 90,
    },
    stops: 0,
    duration: "1h 30m",
  },
  {
    id: 6,
    airlineName: "AirAsia India",
    airlineModel: "Airbus A320",
    airlineCode: "I5",
    fromAirport: {
      code: "BLR",
      name: "Kempegowda International Airport",
      city: "Bengaluru",
    },
    toAirport: {
      code: "CCU",
      name: "Netaji Subhas Chandra Bose International Airport",
      city: "Kolkata",
    },
    departureTime: "2024-04-27T12:45:00",
    arrivalTime: "2024-04-27T15:15:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 510,
      children: 360,
      infant: 100,
    },
    stops: 0,
    duration: "2h 30m",
  },
  {
    id: 7,
    airlineName: "Air India",
    airlineModel: "Boeing 787",
    airlineCode: "AI",
    fromAirport: {
      code: "HYD",
      name: "Rajiv Gandhi International Airport",
      city: "Hyderabad",
    },
    toAirport: {
      code: "DEL",
      name: "Indira Gandhi International Airport",
      city: "Delhi",
    },
    departureTime: "2024-04-27T10:30:00",
    arrivalTime: "2024-04-27T13:00:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 540,
      children: 390,
      infant: 110,
    },
    stops: 0,
    duration: "2h 30m",
  },
  {
    id: 8,
    airlineName: "IndiGo",
    airlineModel: "Airbus A320neo",
    airlineCode: "6E",
    fromAirport: {
      code: "DEL",
      name: "Indira Gandhi International Airport",
      city: "Delhi",
    },
    toAirport: {
      code: "HYD",
      name: "Rajiv Gandhi International Airport",
      city: "Hyderabad",
    },
    departureTime: "2024-04-27T08:00:00",
    arrivalTime: "2024-04-27T10:30:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 570,
      children: 410,
      infant: 120,
    },
    stops: 0,
    duration: "2h 30m",
  },
  {
    id: 9,
    airlineName: "SpiceJet",
    airlineModel: "Boeing 737",
    airlineCode: "SG",
    fromAirport: {
      code: "AMD",
      name: "Sardar Vallabhbhai Patel International Airport",
      city: "Ahmedabad",
    },
    toAirport: {
      code: "DEL",
      name: "Indira Gandhi International Airport",
      city: "Delhi",
    },
    departureTime: "2024-04-27T11:15:00",
    arrivalTime: "2024-04-27T13:45:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 490,
      children: 350,
      infant: 100,
    },
    stops: 0,
    duration: "2h 30m",
  },
  {
    id: 10,
    airlineName: "GoAir",
    airlineModel: "Airbus A320neo",
    airlineCode: "G8",
    fromAirport: {
      code: "DEL",
      name: "Indira Gandhi International Airport",
      city: "Delhi",
    },
    toAirport: {
      code: "BOM",
      name: "Chhatrapati Shivaji Maharaj International Airport",
      city: "Mumbai",
    },
    departureTime: "2024-04-27T07:45:00",
    arrivalTime: "2024-04-27T10:15:00",
    flightTakeoffDate: "2024-04-27",
    prices: {
      adult: 530,
      children: 380,
      infant: 110,
    },
    stops: 1,
    duration: "2h 30m",
  },
];
